version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.app
    image: phi-classifier-app:latest
    env_file: ./app.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - uploads-data:/app/uploads
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../web/static:/var/www/static:ro
      - uploads-data:/var/www/uploads:ro
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - backend
      - frontend

networks:
  backend: {}
  frontend: {}

volumes:
  redis-data: {}
  uploads-data: {}
